name: guildkit-local

services:
  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: guildkit
      POSTGRES_PASSWORD: guildkit
      POSTGRES_DB: guildkit
      # With this configuration, password is no longer required to login PostgreSQL
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - guildkit-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "--username=guildkit", "--dbname=guildkit", "--host=localhost", "--port=5432" ]
      interval: 1s
      timeout: 1m

  storage:
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: guildkit
      MINIO_ROOT_PASSWORD: guildkit
    ports:
      - "9000:9000" # API
      - "9001:9001" # Admin console
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - guildkit-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 1s
      timeout: 1m

volumes:
  guildkit-db: {}
  guildkit-storage: {}
