[tools]
node = { version = "24" }
"npm:nushell" = "latest"

[tasks]
  [tasks.dev]
  depends = [ "sync" ]
  run = "next dev"

  [tasks.start]
  run = "next start"

  [tasks.db]
  run = "psql --username=guildkit --dbname=guildkit --host=localhost --port=5432"

  [tasks.resetdb-demo]
  run = "jiti ./scripts/resetdb-demo.ts && drizzle-kit migrate && jiti ./scripts/seed.ts"

  [tasks.build]
  depends = [ "sync" ]
  run = "next build"
  env = { NODE_ENV = "production" }

  [tasks.lint]
  depends = [ "sync" ]
  run = [
    "tsc --noEmit",
    "eslint"
  ]

  [tasks.fix]
  depends = [ "sync" ]
  run = "eslint --fix"

  [tasks.test]
  run = "vitest run"

  [tasks.clean]
  run = "git clean -dX --exclude=\"!.env\" --force"

  [tasks.refresh]
  depends = [ "clean" ]
  run = [
    "rm --force ./pnpm-lock.yaml",
    "corepack enable",
    "corepack up",
    "pnpm install"
  ]

  [tasks.sync]
  depends = [ "sync:*" ]

  # TODO disabled until GA
  #[tasks.release]
  #run = "npm publish --access public --non-interactive"

[hooks]
postinstall = [
  "corepack enable",
  "pnpm install --frozen-lockfile",
  "nu ./scripts/scripts.nu sync --seed"
]

[env]
_.path = "./node_modules/.bin"

[settings]
jobs = 8

# Required for hooks as of 2025.10
# https://mise.jdx.dev/hooks.html
experimental = true
