name: GitHub Actions

on:
  push:
    branches:
      - main
  schedule:
    - cron: "12 4 * * *" # everyday at 4:12 AM UTC

permissions: {}

jobs:
  resetdb-demo:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DEMO_MAIN_DATABASE_URL }}
      SERVER_ENV: "ci-periodic"
      BETTER_AUTH_URL: "http://localhost:3000"
      BETTER_AUTH_SECRET: dummy
      GOOGLE_CLIENT_ID: dummy
      GITHUB_CLIENT_ID: dummy
      GOOGLE_CLIENT_SECRET: dummy
      GITHUB_CLIENT_SECRET: dummy
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@c53b9236f0b3370f31520f8b142f141256d839c6 # v3.6.0
        with:
          install: true
          cache: true

      - run: mise install
      - run: mise resetdb-demo
