name: GitHub Actions

on:
  push:
    branches:
      - main
  schedule:
    - cron: "12 4 * * *" # everyday at 4:12 AM UTC

permissions:
  contents: read

jobs:
  resetdb-demo:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DEMO_MAIN_DATABASE_URL }}
      SERVER_ENV: "ci-periodic"
      BETTER_AUTH_URL: "http://localhost:3000"
      BETTER_AUTH_SECRET: dummy_67Vl2BsxaiKFX41eYaGqvCHHQ4
      GOOGLE_CLIENT_ID: dummy
      GITHUB_CLIENT_ID: dummy
      GOOGLE_CLIENT_SECRET: dummy
      GITHUB_CLIENT_SECRET: dummy
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0
        with:
          install: true
          cache: true

      - run: mise install
      - run: mise resetdb-demo
